---
- hosts: 127.0.0.1
  connection: local
  sudo: yes
  vars:
    go_url: "https://storage.googleapis.com/golang/go1.5.3.linux-amd64.tar.gz"
    prefix_dir: "/usr/local"
  tasks:
    - name: install mercurial
      yum: name=hg state=present
    - name: install tar
      yum: name=tar state=present
    - shell: curl -o go.tar.gz {{go_url}}
      args:
        chdir: "{{prefix_dir}}/src"
        creates: "go.tar.gz"
    - shell: tar xvf src/go.tar.gz
      args:
        chdir: "{{prefix_dir}}"
        creates: "{{prefix_dir}}/go/bin/go"
