---
- hosts: 127.0.0.1
  connection: local
  sudo: yes
  vars:
    tig_repo: "https://github.com/jonas/tig.git"
    build_env: "LDLIBS=-lncursesw CFLAGS=-I/usr/include/ncursesw"
    build_option: "prefix=/usr/local"
    src_dir: "/usr/local/src"
  tasks:
    # yum install
    - name: install gcc
      yum: name=gcc state=present
    - git: repo={{tig_repo}}
           dest={{src_dir}}/tig
           version=master
           accept_hostkey=yes
           update=no
    # build tig
    - shell: "{{build_env}} make install {{build_option}}"
      args:
        chdir: "{{src_dir}}/tig"
        creates: "/usr/local/bin/tig"
