---
- include: jdk.yml
- hosts: 127.0.0.1
  connection: local
  become: yes
  vars:
    version: "3.3.9"
    url: "http://ftp.meisei-u.ac.jp/mirror/apache/dist/maven/maven-3/{{version}}/binaries/apache-maven-{{version}}-bin.tar.gz"
    prefix_dir: "/usr/local"
  tasks:
    - get_url: url={{url}} dest=/tmp/maven.tar.gz mode=0644
    - unarchive:
      args:
        src: "/tmp/maven.tar.gz"
        dest: "{{prefix_dir}}"
        creates: "{{prefix_dir}}/apache-maven-{{version}}"
    - file: src={{prefix_dir}}/apache-maven-{{version}}
            dest={{prefix_dir}}/maven
            state=link


