---
- hosts: 127.0.0.1
  connection: local
  sudo: yes
  vars:
    luajit_repo: "http://luajit.org/git/luajit-2.0.git"
    vim_repo: "https://vim.googlecode.com/hg/"
    vim_configure: "--prefix=/usr/local --with-features=huge --enable-multibyte --enable-luainterp --with-luajit --enable-fail-if-missing"
    src_dir: "/usr/loacl/src"
  tasks:
    # yum install
    - name: install gcc
      yum: name=gcc state=present
    - name: install ncurses
      yum: name=ncurses state=present
    - name: install ncurses-devel
      yum: name=ncurses-devel state=present
    - name: install mercurial
      yum: name=mercurial state=present
    - name: install lua
      yum: name=lua state=present
    - name: install lua-devel
      yum: name=lua-devel state=present
    # luajit
    - git: repo={{luajit_repo}}
           dest={{src_dir}}/luajit
           version=master
           accept_hostkey=yes
           update=no
    # build luajit
    - shell: make && make install
      args:
        chdir: "{{src_dir}}/luajit"
        creates: "/usr/local/lib/libluajit-5.1.so"
    - hg: repo={{vim_repo}}
          dest={{src_dir}}/vim
    - shell: ./configure {{vim_configure}} && make && make install
      args:
        chdir: "{{src_dir}}/vim"
        creates: "/usr/local/bin/vim"
    - copy: src=files/ld_lib_path.sh dest=/etc/profile.d/ld_lib_path.sh
    # remove vim-mininal
    - name: remove pre-installed vim
      yum: name="vim-minimal" state=absent
