---
- hosts: 127.0.0.1
  connection: local
  sudo: yes
  vars:
    yum_packages:
      - make
      - gcc
      - git
      - ncurses
      - ncurses-devel
      - lua
      - lua-devel
    luajit_repo: "http://luajit.org/git/luajit-2.0.git"
    vim_repo: "https://github.com/vim/vim"
    vim_configure: "--prefix=/usr/local --with-features=huge --enable-multibyte --enable-luainterp --with-luajit --enable-fail-if-missing"
    src_dir: "/usr/local/src"
  tasks:
    # yum install
    - yum: name={{ item }} state=present
      with_items: yum_packages
    # luajit
    - git: repo={{luajit_repo}}
           dest={{src_dir}}/luajit
           version=master
           accept_hostkey=yes
           update=no
    # build luajit
    - shell: make && make install
      args:
        chdir: "{{src_dir}}/luajit"
        creates: "/usr/local/lib/libluajit-5.1.so"
    - git: repo={{vim_repo}}
           dest={{src_dir}}/vim
           version=master
           accept_hostkey=yes
           update=no
    # build vim
    - shell: ./configure {{vim_configure}} && make && make install
      args:
        chdir: "{{src_dir}}/vim"
        creates: "/usr/local/bin/vim"
    - copy: src=files/ld_lib_path.sh dest=/etc/profile.d/ld_lib_path.sh
    # remove vim-mininal
    - name: remove pre-installed vim
      yum: name="vim-minimal" state=absent
