---
- hosts: 127.0.0.1
  connection: local
  sudo: yes
  vars:
    hub_repo: "https://github.com/github/hub.git"
    prefix_dir: "/usr/local"
    src_dir: "/usr/loacl/src"
  tasks:
    - name: install rake
      yum: name=rubygem-rake state=present
    - git: repo={{hub_repo}}
           dest={{src_dir}}/hub
           version=master
           accept_hostkey=yes
           update=no
    - shell: rake install {{prefix_dir}}
      args:
        chdir: "{{src_dir}}/hub"
        creates: "/usr/local/bin/hub"
