---
- hosts: 127.0.0.1
  connection: local
  sudo: yes
  vars:
    libevent_url: "https://sourceforge.net/projects/levent/files/release-2.0.22-stable/libevent-2.0.22-stable.tar.gz"
    libevent_file: "libevent-2.0.22-stable.tar.gz"
    libevent_conf: "/etc/ld.so.conf.d/libevent.conf"
    tmux_url: "http://downloads.sourceforge.net/project/tmux/tmux/tmux-1.9/tmux-1.9a.tar.gz"
    tmux_file: "tmux-1.9a.tar.gz"
    src_dir: "/usr/local/src"
    lib_dir: "/usr/local/lib"
  tasks:
    # install libevent
    - shell: curl -L -o {{libevent_file}} {{libevent_url}} 
      args:
        chdir: "{{src_dir}}"
        creates: "{{libevent_file}}"
    - shell: tar xvf {{libevent_file}}
      args:
        chdir: "{{src_dir}}"
        creates: "{{src_dir}}/libevent-2.0.22-stable"
    - shell: ./configure && make && make install
      args:
        chdir: "{{src_dir}}/libevent-2.0.22-stable"
        creates: "{{lib_dir}}/libevent.a"
    # ldconfig
    - shell: echo "{{lib_dir}}" > {{libevent_conf}} && ldconfig

    # install tmux
    - shell: curl -L -o {{tmux_file}} {{tmux_url}}
      args:
        chdir: "{{src_dir}}"
        creates: "{{tmux_file}}"
    - shell: tar xvf {{tmux_file}}
      args:
        chdir: "{{src_dir}}"
        creates: "{{src_dir}}/tmux-1.9a"
    - shell: ./configure && make && make install
      args:
        chdir: "{{src_dir}}/tmux-1.9a"
        creates: "/usr/local/bin/tmux"
