---
- hosts: 127.0.0.1
  connection: local
  become: yes
  vars:
    users:
      - vagrant
      - root
  tasks:
    - yum: name=zsh state=present
    - user: name={{ item }} shell=/bin/zsh
      with_items: users
