---
- include: java.yml
- hosts: 127.0.0.1
  connection: local
  become: no
  vars:
    lein_url: "https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein"
    bin_dir: "~/bin"
  tasks:
    - file: path={{bin_dir}} state=directory
    - get_url: url={{lein_url}} dest={{bin_dir}}/lein mode=0755
    - shell: ./lein self-install
      args:
        chdir: "{{bin_dir}}"
        creates: ~/.lein/self-installs
