---
- hosts: 127.0.0.1
  connection: local
  sudo: yes
  vars:
    lein_url: "https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein"
    bin_dir: "~/bin"
  tasks:
    - name: install openjdk
      yum: name=java-1.7.0-openjdk.x86_64 state=present
    - file: path={{bin_dir}} state=directory
    - get_url: url={{lein_url}} dest={{bin_dir}}/lein mode=0755
    - shell: ./lein self-install
      args:
        chdir: "{{bin_dir}}"
        creates: ~/.lein/self-installs

